// <auto-generated />
using System;
using ChemJourney.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChemJourney.Data.Migrations
{
    [DbContext(typeof(ChemJourneyDbContext))]
    [Migration("20240315204353_SeedQuizzes")]
    partial class SeedQuizzes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChemJourney.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id of the category");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the category");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasComment("Categories that a post might have.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Organic Chemistry"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physical Chemistry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Analytical Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Inorganic Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Biochemistry"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Undefined"
                        });
                });

            modelBuilder.Entity("ChemJourney.Data.Models.ChemicalGroupBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The ID of the chemical group block.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("The Name of the chemical group block.");

                    b.HasKey("Id");

                    b.ToTable("ChemicalGroupBlocks");

                    b.HasComment("The types of chemical group blocks that exist in the periodic table.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nonmetal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alkali Metal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alkaline Earth Metal"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lanthanide"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Actinide"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Transition Metal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Post-Transition Metal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Metalloid"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Halogen"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Noble Gas"
                        });
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The atomic number of the element");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("AtomicMass")
                        .HasColumnType("float")
                        .HasComment("The atomic mass of the element");

                    b.Property<double?>("BoilingPoint")
                        .HasColumnType("float")
                        .HasComment("The boiling point of the element");

                    b.Property<int>("ChemicalGroupBlockId")
                        .HasColumnType("int");

                    b.Property<double?>("MeltingPoint")
                        .HasColumnType("float")
                        .HasComment("The melting point of the element");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("The number of the element");

                    b.Property<string>("OxidationStates")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("The standart state of the element");

                    b.Property<string>("StandardState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("The standard state of the element");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("The symbol of the element");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalGroupBlockId");

                    b.ToTable("Elements");

                    b.HasComment("The elements of the Periodic Table");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtomicMass = 1.008,
                            BoilingPoint = 20.280000000000001,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 13.81,
                            Name = "Hydrogen",
                            OxidationStates = "+1, -1",
                            StandardState = "Gas",
                            Symbol = "H"
                        },
                        new
                        {
                            Id = 2,
                            AtomicMass = 4.0026000000000002,
                            BoilingPoint = 4.2199999999999998,
                            ChemicalGroupBlockId = 10,
                            MeltingPoint = 0.94999999999999996,
                            Name = "Helium",
                            OxidationStates = "0",
                            StandardState = "Gas",
                            Symbol = "He"
                        },
                        new
                        {
                            Id = 3,
                            AtomicMass = 7.0,
                            BoilingPoint = 1615.0,
                            ChemicalGroupBlockId = 2,
                            MeltingPoint = 453.64999999999998,
                            Name = "Lithium",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "Li"
                        },
                        new
                        {
                            Id = 4,
                            AtomicMass = 9.0121830000000003,
                            BoilingPoint = 2744.0,
                            ChemicalGroupBlockId = 3,
                            MeltingPoint = 1560.0,
                            Name = "Beryllium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Be"
                        },
                        new
                        {
                            Id = 5,
                            AtomicMass = 10.81,
                            BoilingPoint = 4273.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 2348.0,
                            Name = "Boron",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "B"
                        },
                        new
                        {
                            Id = 6,
                            AtomicMass = 12.010999999999999,
                            BoilingPoint = 4098.0,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 3823.0,
                            Name = "Carbon",
                            OxidationStates = "+4, +2, -4",
                            StandardState = "Solid",
                            Symbol = "C"
                        },
                        new
                        {
                            Id = 7,
                            AtomicMass = 14.007,
                            BoilingPoint = 77.359999999999999,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 63.149999999999999,
                            Name = "Nitrogen",
                            OxidationStates = "+5, +4, +3, +2, +1, -1, -2, -3",
                            StandardState = "Gas",
                            Symbol = "N"
                        },
                        new
                        {
                            Id = 8,
                            AtomicMass = 15.999000000000001,
                            BoilingPoint = 90.200000000000003,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 54.359999999999999,
                            Name = "Oxygen",
                            OxidationStates = "-2",
                            StandardState = "Gas",
                            Symbol = "O"
                        },
                        new
                        {
                            Id = 9,
                            AtomicMass = 18.9984,
                            BoilingPoint = 85.030000000000001,
                            ChemicalGroupBlockId = 9,
                            MeltingPoint = 53.530000000000001,
                            Name = "Fluorine",
                            OxidationStates = "-1",
                            StandardState = "Gas",
                            Symbol = "F"
                        },
                        new
                        {
                            Id = 10,
                            AtomicMass = 20.18,
                            BoilingPoint = 27.07,
                            ChemicalGroupBlockId = 10,
                            MeltingPoint = 24.559999999999999,
                            Name = "Neon",
                            OxidationStates = "0",
                            StandardState = "Gas",
                            Symbol = "Ne"
                        },
                        new
                        {
                            Id = 11,
                            AtomicMass = 22.989769299999999,
                            BoilingPoint = 1156.0,
                            ChemicalGroupBlockId = 2,
                            MeltingPoint = 370.94999999999999,
                            Name = "Sodium",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "Na"
                        },
                        new
                        {
                            Id = 12,
                            AtomicMass = 24.305,
                            BoilingPoint = 1363.0,
                            ChemicalGroupBlockId = 3,
                            MeltingPoint = 923.0,
                            Name = "Magnesium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Mg"
                        },
                        new
                        {
                            Id = 13,
                            AtomicMass = 26.981538,
                            BoilingPoint = 2792.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 933.43700000000001,
                            Name = "Aluminum",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Al"
                        },
                        new
                        {
                            Id = 14,
                            AtomicMass = 28.085000000000001,
                            BoilingPoint = 3538.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 1687.0,
                            Name = "Silicon",
                            OxidationStates = "+4, +2, -4",
                            StandardState = "Solid",
                            Symbol = "Si"
                        },
                        new
                        {
                            Id = 15,
                            AtomicMass = 30.973762000000001,
                            BoilingPoint = 553.64999999999998,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 317.30000000000001,
                            Name = "Phosphorus",
                            OxidationStates = "+5, +3, -3",
                            StandardState = "Solid",
                            Symbol = "P"
                        },
                        new
                        {
                            Id = 16,
                            AtomicMass = 32.07,
                            BoilingPoint = 717.75,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 388.36000000000001,
                            Name = "Sulfur",
                            OxidationStates = "+6, +4, -2",
                            StandardState = "Solid",
                            Symbol = "S"
                        },
                        new
                        {
                            Id = 17,
                            AtomicMass = 35.450000000000003,
                            BoilingPoint = 239.11000000000001,
                            ChemicalGroupBlockId = 9,
                            MeltingPoint = 171.65000000000001,
                            Name = "Chlorine",
                            OxidationStates = "+7, +5, +1, -1",
                            StandardState = "Gas",
                            Symbol = "Cl"
                        },
                        new
                        {
                            Id = 18,
                            AtomicMass = 39.899999999999999,
                            BoilingPoint = 87.299999999999997,
                            ChemicalGroupBlockId = 10,
                            MeltingPoint = 83.799999999999997,
                            Name = "Argon",
                            OxidationStates = "0",
                            StandardState = "Gas",
                            Symbol = "Ar"
                        },
                        new
                        {
                            Id = 19,
                            AtomicMass = 39.098300000000002,
                            BoilingPoint = 1032.0,
                            ChemicalGroupBlockId = 2,
                            MeltingPoint = 336.52999999999997,
                            Name = "Potassium",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "K"
                        },
                        new
                        {
                            Id = 20,
                            AtomicMass = 40.079999999999998,
                            BoilingPoint = 1757.0,
                            ChemicalGroupBlockId = 3,
                            MeltingPoint = 1115.0,
                            Name = "Calcium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Ca"
                        },
                        new
                        {
                            Id = 21,
                            AtomicMass = 44.955910000000003,
                            BoilingPoint = 3109.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1814.0,
                            Name = "Scandium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Sc"
                        },
                        new
                        {
                            Id = 22,
                            AtomicMass = 47.866999999999997,
                            BoilingPoint = 3560.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1941.0,
                            Name = "Titanium",
                            OxidationStates = "+4, +3, +2",
                            StandardState = "Solid",
                            Symbol = "Ti"
                        },
                        new
                        {
                            Id = 23,
                            AtomicMass = 50.941499999999998,
                            BoilingPoint = 3680.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2183.0,
                            Name = "Vanadium",
                            OxidationStates = "+5, +4, +3, +2",
                            StandardState = "Solid",
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 24,
                            AtomicMass = 51.996000000000002,
                            BoilingPoint = 2944.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2180.0,
                            Name = "Chromium",
                            OxidationStates = "+6, +3, +2",
                            StandardState = "Solid",
                            Symbol = "Cr"
                        },
                        new
                        {
                            Id = 25,
                            AtomicMass = 54.938040000000001,
                            BoilingPoint = 2334.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1519.0,
                            Name = "Manganese",
                            OxidationStates = "+7, +4, +3, +2",
                            StandardState = "Solid",
                            Symbol = "Mn"
                        },
                        new
                        {
                            Id = 26,
                            AtomicMass = 55.840000000000003,
                            BoilingPoint = 3134.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1811.0,
                            Name = "Iron",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Fe"
                        },
                        new
                        {
                            Id = 27,
                            AtomicMass = 58.933190000000003,
                            BoilingPoint = 3200.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1768.0,
                            Name = "Cobalt",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Co"
                        },
                        new
                        {
                            Id = 28,
                            AtomicMass = 58.692999999999998,
                            BoilingPoint = 3186.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1728.0,
                            Name = "Nickel",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Ni"
                        },
                        new
                        {
                            Id = 29,
                            AtomicMass = 63.549999999999997,
                            BoilingPoint = 2835.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1357.77,
                            Name = "Copper",
                            OxidationStates = "+2, +1",
                            StandardState = "Solid",
                            Symbol = "Cu"
                        },
                        new
                        {
                            Id = 30,
                            AtomicMass = 65.400000000000006,
                            BoilingPoint = 1180.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 692.67999999999995,
                            Name = "Zinc",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Zn"
                        },
                        new
                        {
                            Id = 31,
                            AtomicMass = 69.722999999999999,
                            BoilingPoint = 2477.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 302.91000000000003,
                            Name = "Gallium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Ga"
                        },
                        new
                        {
                            Id = 32,
                            AtomicMass = 72.629999999999995,
                            BoilingPoint = 3106.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 1211.4000000000001,
                            Name = "Germanium",
                            OxidationStates = "+4, +2",
                            StandardState = "Solid",
                            Symbol = "Ge"
                        },
                        new
                        {
                            Id = 33,
                            AtomicMass = 74.921589999999995,
                            BoilingPoint = 887.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 1090.0,
                            Name = "Arsenic",
                            OxidationStates = "+5, +3, -3",
                            StandardState = "Solid",
                            Symbol = "As"
                        },
                        new
                        {
                            Id = 34,
                            AtomicMass = 78.969999999999999,
                            BoilingPoint = 958.0,
                            ChemicalGroupBlockId = 1,
                            MeltingPoint = 493.64999999999998,
                            Name = "Selenium",
                            OxidationStates = "+6, +4, -2",
                            StandardState = "Solid",
                            Symbol = "Se"
                        },
                        new
                        {
                            Id = 35,
                            AtomicMass = 79.900000000000006,
                            BoilingPoint = 331.94999999999999,
                            ChemicalGroupBlockId = 9,
                            MeltingPoint = 265.94999999999999,
                            Name = "Bromine",
                            OxidationStates = "+7, +1, -1",
                            StandardState = "Liquid",
                            Symbol = "Br"
                        },
                        new
                        {
                            Id = 36,
                            AtomicMass = 83.799999999999997,
                            BoilingPoint = 119.93000000000001,
                            ChemicalGroupBlockId = 10,
                            MeltingPoint = 115.79000000000001,
                            Name = "Krypton",
                            OxidationStates = "0",
                            StandardState = "Gas",
                            Symbol = "Kr"
                        },
                        new
                        {
                            Id = 37,
                            AtomicMass = 85.468000000000004,
                            BoilingPoint = 961.0,
                            ChemicalGroupBlockId = 2,
                            MeltingPoint = 312.45999999999998,
                            Name = "Rubidium",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "Rb"
                        },
                        new
                        {
                            Id = 38,
                            AtomicMass = 87.620000000000005,
                            BoilingPoint = 1655.0,
                            ChemicalGroupBlockId = 3,
                            MeltingPoint = 1050.0,
                            Name = "Strontium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Sr"
                        },
                        new
                        {
                            Id = 39,
                            AtomicMass = 88.905839999999998,
                            BoilingPoint = 3618.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1795.0,
                            Name = "Yttrium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Y"
                        },
                        new
                        {
                            Id = 40,
                            AtomicMass = 91.219999999999999,
                            BoilingPoint = 4682.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2128.0,
                            Name = "Zirconium",
                            OxidationStates = "+4",
                            StandardState = "Solid",
                            Symbol = "Zr"
                        },
                        new
                        {
                            Id = 41,
                            AtomicMass = 92.906369999999995,
                            BoilingPoint = 5017.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2750.0,
                            Name = "Niobium",
                            OxidationStates = "+5, +3",
                            StandardState = "Solid",
                            Symbol = "Nb"
                        },
                        new
                        {
                            Id = 42,
                            AtomicMass = 95.950000000000003,
                            BoilingPoint = 4912.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2896.0,
                            Name = "Molybdenum",
                            OxidationStates = "+6",
                            StandardState = "Solid",
                            Symbol = "Mo"
                        },
                        new
                        {
                            Id = 43,
                            AtomicMass = 96.906360000000006,
                            BoilingPoint = 4538.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2430.0,
                            Name = "Technetium",
                            OxidationStates = "+7, +6, +4",
                            StandardState = "Solid",
                            Symbol = "Tc"
                        },
                        new
                        {
                            Id = 44,
                            AtomicMass = 101.09999999999999,
                            BoilingPoint = 4423.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2607.0,
                            Name = "Ruthenium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Ru"
                        },
                        new
                        {
                            Id = 45,
                            AtomicMass = 102.9055,
                            BoilingPoint = 3968.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2237.0,
                            Name = "Rhodium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Rh"
                        },
                        new
                        {
                            Id = 46,
                            AtomicMass = 106.42,
                            BoilingPoint = 3236.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1828.05,
                            Name = "Palladium",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Pd"
                        },
                        new
                        {
                            Id = 47,
                            AtomicMass = 107.86799999999999,
                            BoilingPoint = 2435.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1234.9300000000001,
                            Name = "Silver",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "Ag"
                        },
                        new
                        {
                            Id = 48,
                            AtomicMass = 112.41,
                            BoilingPoint = 1040.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 594.22000000000003,
                            Name = "Cadmium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Cd"
                        },
                        new
                        {
                            Id = 49,
                            AtomicMass = 114.818,
                            BoilingPoint = 2345.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 429.75,
                            Name = "Indium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "In"
                        },
                        new
                        {
                            Id = 50,
                            AtomicMass = 118.70999999999999,
                            BoilingPoint = 2875.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 505.07999999999998,
                            Name = "Tin",
                            OxidationStates = "+4, +2",
                            StandardState = "Solid",
                            Symbol = "Sn"
                        },
                        new
                        {
                            Id = 51,
                            AtomicMass = 121.76000000000001,
                            BoilingPoint = 1860.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 903.77999999999997,
                            Name = "Antimony",
                            OxidationStates = "+5, +3, -3",
                            StandardState = "Solid",
                            Symbol = "Sb"
                        },
                        new
                        {
                            Id = 52,
                            AtomicMass = 127.59999999999999,
                            BoilingPoint = 1261.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 722.65999999999997,
                            Name = "Tellurium",
                            OxidationStates = "+6, +4, -2",
                            StandardState = "Solid",
                            Symbol = "Te"
                        },
                        new
                        {
                            Id = 53,
                            AtomicMass = 126.9045,
                            BoilingPoint = 457.55000000000001,
                            ChemicalGroupBlockId = 9,
                            MeltingPoint = 386.85000000000002,
                            Name = "Iodine",
                            OxidationStates = "+7, +5, +1, -1",
                            StandardState = "Solid",
                            Symbol = "I"
                        },
                        new
                        {
                            Id = 54,
                            AtomicMass = 131.28999999999999,
                            BoilingPoint = 165.03,
                            ChemicalGroupBlockId = 10,
                            MeltingPoint = 161.36000000000001,
                            Name = "Xenon",
                            OxidationStates = "0",
                            StandardState = "Gas",
                            Symbol = "Xe"
                        },
                        new
                        {
                            Id = 55,
                            AtomicMass = 132.905452,
                            BoilingPoint = 944.0,
                            ChemicalGroupBlockId = 2,
                            MeltingPoint = 301.58999999999997,
                            Name = "Cesium",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "Cs"
                        },
                        new
                        {
                            Id = 56,
                            AtomicMass = 137.33000000000001,
                            BoilingPoint = 2170.0,
                            ChemicalGroupBlockId = 3,
                            MeltingPoint = 1000.0,
                            Name = "Barium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Ba"
                        },
                        new
                        {
                            Id = 57,
                            AtomicMass = 138.90549999999999,
                            BoilingPoint = 3737.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1191.0,
                            Name = "Lanthanum",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "La"
                        },
                        new
                        {
                            Id = 58,
                            AtomicMass = 140.11600000000001,
                            BoilingPoint = 3697.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1071.0,
                            Name = "Cerium",
                            OxidationStates = "+4, +3",
                            StandardState = "Solid",
                            Symbol = "Ce"
                        },
                        new
                        {
                            Id = 59,
                            AtomicMass = 140.90765999999999,
                            BoilingPoint = 3793.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1204.0,
                            Name = "Praseodymium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Pr"
                        },
                        new
                        {
                            Id = 60,
                            AtomicMass = 144.24000000000001,
                            BoilingPoint = 3347.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1294.0,
                            Name = "Neodymium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Nd"
                        },
                        new
                        {
                            Id = 61,
                            AtomicMass = 144.91275999999999,
                            BoilingPoint = 3273.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1315.0,
                            Name = "Promethium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Pm"
                        },
                        new
                        {
                            Id = 62,
                            AtomicMass = 150.40000000000001,
                            BoilingPoint = 2067.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1347.0,
                            Name = "Samarium",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Sm"
                        },
                        new
                        {
                            Id = 63,
                            AtomicMass = 151.964,
                            BoilingPoint = 1802.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1095.0,
                            Name = "Europium",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Eu"
                        },
                        new
                        {
                            Id = 64,
                            AtomicMass = 157.19999999999999,
                            BoilingPoint = 3546.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1586.0,
                            Name = "Gadolinium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Gd"
                        },
                        new
                        {
                            Id = 65,
                            AtomicMass = 158.92535000000001,
                            BoilingPoint = 3503.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1629.0,
                            Name = "Terbium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Tb"
                        },
                        new
                        {
                            Id = 66,
                            AtomicMass = 162.5,
                            BoilingPoint = 2840.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1685.0,
                            Name = "Dysprosium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Dy"
                        },
                        new
                        {
                            Id = 67,
                            AtomicMass = 164.93033,
                            BoilingPoint = 2973.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1747.0,
                            Name = "Holmium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Ho"
                        },
                        new
                        {
                            Id = 68,
                            AtomicMass = 167.25999999999999,
                            BoilingPoint = 3141.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1802.0,
                            Name = "Erbium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Er"
                        },
                        new
                        {
                            Id = 69,
                            AtomicMass = 168.93422000000001,
                            BoilingPoint = 2223.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1818.0,
                            Name = "Thulium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Tm"
                        },
                        new
                        {
                            Id = 70,
                            AtomicMass = 173.05000000000001,
                            BoilingPoint = 1469.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1092.0,
                            Name = "Ytterbium",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Yb"
                        },
                        new
                        {
                            Id = 71,
                            AtomicMass = 174.96680000000001,
                            BoilingPoint = 3675.0,
                            ChemicalGroupBlockId = 4,
                            MeltingPoint = 1936.0,
                            Name = "Lutetium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Lu"
                        },
                        new
                        {
                            Id = 72,
                            AtomicMass = 178.49000000000001,
                            BoilingPoint = 4876.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2506.0,
                            Name = "Hafnium",
                            OxidationStates = "Solid",
                            StandardState = "Solid",
                            Symbol = "Hf"
                        },
                        new
                        {
                            Id = 73,
                            AtomicMass = 180.9479,
                            BoilingPoint = 5731.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 3290.0,
                            Name = "Tantalum",
                            OxidationStates = "+5",
                            StandardState = "Solid",
                            Symbol = "Ta"
                        },
                        new
                        {
                            Id = 74,
                            AtomicMass = 183.84,
                            BoilingPoint = 5828.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 3695.0,
                            Name = "Tungsten",
                            OxidationStates = "+6",
                            StandardState = "Solid",
                            Symbol = "W"
                        },
                        new
                        {
                            Id = 75,
                            AtomicMass = 186.20699999999999,
                            BoilingPoint = 5869.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 3459.0,
                            Name = "Rhenium",
                            OxidationStates = "+7, +6, +4",
                            StandardState = "Solid",
                            Symbol = "Re"
                        },
                        new
                        {
                            Id = 76,
                            AtomicMass = 190.19999999999999,
                            BoilingPoint = 5285.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 3306.0,
                            Name = "Osmium",
                            OxidationStates = "+4, +3",
                            StandardState = "Solid",
                            Symbol = "Os"
                        },
                        new
                        {
                            Id = 77,
                            AtomicMass = 192.22,
                            BoilingPoint = 4701.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2719.0,
                            Name = "Iridium",
                            OxidationStates = "+4, +3",
                            StandardState = "Solid",
                            Symbol = "Ir"
                        },
                        new
                        {
                            Id = 78,
                            AtomicMass = 195.08000000000001,
                            BoilingPoint = 4098.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 2041.55,
                            Name = "Platinum",
                            OxidationStates = "+4, +2",
                            StandardState = "Solid",
                            Symbol = "Pt"
                        },
                        new
                        {
                            Id = 79,
                            AtomicMass = 196.96656999999999,
                            BoilingPoint = 3129.0,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 1337.3299999999999,
                            Name = "Gold",
                            OxidationStates = "+3, +1",
                            StandardState = "Solid",
                            Symbol = "Au"
                        },
                        new
                        {
                            Id = 80,
                            AtomicMass = 200.59,
                            BoilingPoint = 629.88,
                            ChemicalGroupBlockId = 6,
                            MeltingPoint = 234.31999999999999,
                            Name = "Mercury",
                            OxidationStates = "+2, +1",
                            StandardState = "Liquid",
                            Symbol = "Hg"
                        },
                        new
                        {
                            Id = 81,
                            AtomicMass = 204.38300000000001,
                            BoilingPoint = 1746.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 577.0,
                            Name = "Thallium",
                            OxidationStates = "+3, +1",
                            StandardState = "Solid",
                            Symbol = "Tl"
                        },
                        new
                        {
                            Id = 82,
                            AtomicMass = 207.0,
                            BoilingPoint = 2022.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 600.61000000000001,
                            Name = "Lead",
                            OxidationStates = "+4, +2",
                            StandardState = "Solid",
                            Symbol = "Pb"
                        },
                        new
                        {
                            Id = 83,
                            AtomicMass = 208.9804,
                            BoilingPoint = 1837.0,
                            ChemicalGroupBlockId = 7,
                            MeltingPoint = 544.54999999999995,
                            Name = "Bismuth",
                            OxidationStates = "+5, +3",
                            StandardState = "Solid",
                            Symbol = "Bi"
                        },
                        new
                        {
                            Id = 84,
                            AtomicMass = 208.98242999999999,
                            BoilingPoint = 1235.0,
                            ChemicalGroupBlockId = 8,
                            MeltingPoint = 527.0,
                            Name = "Polonium",
                            OxidationStates = "+4, +2",
                            StandardState = "Solid",
                            Symbol = "Po"
                        },
                        new
                        {
                            Id = 85,
                            AtomicMass = 209.98715000000001,
                            ChemicalGroupBlockId = 9,
                            MeltingPoint = 575.0,
                            Name = "Astatine",
                            OxidationStates = "+7, +5, +3, +1, -1",
                            StandardState = "Solid",
                            Symbol = "At"
                        },
                        new
                        {
                            Id = 86,
                            AtomicMass = 222.01758000000001,
                            BoilingPoint = 211.44999999999999,
                            ChemicalGroupBlockId = 10,
                            MeltingPoint = 202.0,
                            Name = "Radon",
                            OxidationStates = "0",
                            StandardState = "Gas",
                            Symbol = "Rn"
                        },
                        new
                        {
                            Id = 87,
                            AtomicMass = 223.01973000000001,
                            ChemicalGroupBlockId = 2,
                            MeltingPoint = 300.0,
                            Name = "Francium",
                            OxidationStates = "+1",
                            StandardState = "Solid",
                            Symbol = "Fr"
                        },
                        new
                        {
                            Id = 88,
                            AtomicMass = 226.02540999999999,
                            BoilingPoint = 1413.0,
                            ChemicalGroupBlockId = 3,
                            MeltingPoint = 973.0,
                            Name = "Radium",
                            OxidationStates = "+2",
                            StandardState = "Solid",
                            Symbol = "Ra"
                        },
                        new
                        {
                            Id = 89,
                            AtomicMass = 227.02775,
                            BoilingPoint = 3471.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1324.0,
                            Name = "Actinium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Ac"
                        },
                        new
                        {
                            Id = 90,
                            AtomicMass = 232.03800000000001,
                            BoilingPoint = 5061.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 2023.0,
                            Name = "Thorium",
                            OxidationStates = "+4",
                            StandardState = "Solid",
                            Symbol = "Th"
                        },
                        new
                        {
                            Id = 91,
                            AtomicMass = 231.03587999999999,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1845.0,
                            Name = "Protactinium",
                            OxidationStates = "+5, +4",
                            StandardState = "Solid",
                            Symbol = "Pa"
                        },
                        new
                        {
                            Id = 92,
                            AtomicMass = 238.02889999999999,
                            BoilingPoint = 4404.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1408.0,
                            Name = "Uranium",
                            OxidationStates = "+6, +5, +4, +3",
                            StandardState = "Solid",
                            Symbol = "U"
                        },
                        new
                        {
                            Id = 93,
                            AtomicMass = 237.04817199999999,
                            BoilingPoint = 4175.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 917.0,
                            Name = "Neptunium",
                            OxidationStates = "+6, +5, +4, +3",
                            StandardState = "Solid",
                            Symbol = "Np"
                        },
                        new
                        {
                            Id = 94,
                            AtomicMass = 244.0642,
                            BoilingPoint = 3501.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 913.0,
                            Name = "Plutonium",
                            OxidationStates = "+6, +5, +4, +3",
                            StandardState = "Solid",
                            Symbol = "Pu"
                        },
                        new
                        {
                            Id = 95,
                            AtomicMass = 243.06138000000001,
                            BoilingPoint = 2284.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1449.0,
                            Name = "Americium",
                            OxidationStates = "+6, +5, +4, +3",
                            StandardState = "Solid",
                            Symbol = "Am"
                        },
                        new
                        {
                            Id = 96,
                            AtomicMass = 247.07034999999999,
                            BoilingPoint = 3400.0,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1618.0,
                            Name = "Curium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Cm"
                        },
                        new
                        {
                            Id = 97,
                            AtomicMass = 247.07031000000001,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1323.0,
                            Name = "Berkelium",
                            OxidationStates = "+4, +3",
                            StandardState = "Solid",
                            Symbol = "Bk"
                        },
                        new
                        {
                            Id = 98,
                            AtomicMass = 251.07959,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1173.0,
                            Name = "Californium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Cf"
                        },
                        new
                        {
                            Id = 99,
                            AtomicMass = 252.083,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1133.0,
                            Name = "Einsteinium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Es"
                        },
                        new
                        {
                            Id = 100,
                            AtomicMass = 257.09510999999998,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1800.0,
                            Name = "Fermium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Fm"
                        },
                        new
                        {
                            Id = 101,
                            AtomicMass = 258.09843000000001,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1100.0,
                            Name = "Mendelevium",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "Md"
                        },
                        new
                        {
                            Id = 102,
                            AtomicMass = 259.101,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1100.0,
                            Name = "Nobelium",
                            OxidationStates = "+3, +2",
                            StandardState = "Solid",
                            Symbol = "No"
                        },
                        new
                        {
                            Id = 103,
                            AtomicMass = 266.12,
                            ChemicalGroupBlockId = 5,
                            MeltingPoint = 1900.0,
                            Name = "Lawrencium",
                            OxidationStates = "+3",
                            StandardState = "Solid",
                            Symbol = "Lr"
                        },
                        new
                        {
                            Id = 104,
                            AtomicMass = 267.12200000000001,
                            ChemicalGroupBlockId = 6,
                            Name = "Rutherfordium",
                            OxidationStates = "+4",
                            StandardState = "Solid",
                            Symbol = "Rf"
                        },
                        new
                        {
                            Id = 105,
                            AtomicMass = 268.12599999999998,
                            ChemicalGroupBlockId = 6,
                            Name = "Dubnium",
                            OxidationStates = "+5, +4, +3",
                            StandardState = "Solid",
                            Symbol = "Db"
                        },
                        new
                        {
                            Id = 106,
                            AtomicMass = 269.12799999999999,
                            ChemicalGroupBlockId = 6,
                            Name = "Seaborgium",
                            OxidationStates = "+6, +5, +4, +3, 0",
                            StandardState = "Solid",
                            Symbol = "Sg"
                        },
                        new
                        {
                            Id = 107,
                            AtomicMass = 270.13299999999998,
                            ChemicalGroupBlockId = 6,
                            Name = "Bohrium",
                            OxidationStates = "+7, +5, +4, +3",
                            StandardState = "Solid",
                            Symbol = "Bh"
                        },
                        new
                        {
                            Id = 108,
                            AtomicMass = 269.1336,
                            ChemicalGroupBlockId = 6,
                            Name = "Hassium",
                            OxidationStates = "+8, +6, +5, +4, +3, +2",
                            StandardState = "Solid",
                            Symbol = "Hs"
                        },
                        new
                        {
                            Id = 109,
                            AtomicMass = 277.154,
                            ChemicalGroupBlockId = 6,
                            Name = "Meitnerium",
                            OxidationStates = "+9, +8, +6, +4, +3, +1",
                            StandardState = "Solid",
                            Symbol = "Mt"
                        },
                        new
                        {
                            Id = 110,
                            AtomicMass = 282.166,
                            ChemicalGroupBlockId = 6,
                            Name = "Darmstadtium",
                            OxidationStates = "+8, +6, +4, +2, 0",
                            StandardState = "Solid",
                            Symbol = "Ds"
                        },
                        new
                        {
                            Id = 111,
                            AtomicMass = 282.16899999999998,
                            ChemicalGroupBlockId = 6,
                            Name = "Roentgenium",
                            OxidationStates = "+5, +3, +1, -1",
                            StandardState = "Solid",
                            Symbol = "Rg"
                        },
                        new
                        {
                            Id = 112,
                            AtomicMass = 286.17899999999997,
                            ChemicalGroupBlockId = 6,
                            Name = "Copernicium",
                            OxidationStates = "+2, +1, 0",
                            StandardState = "Solid",
                            Symbol = "Cn"
                        },
                        new
                        {
                            Id = 113,
                            AtomicMass = 286.18200000000002,
                            ChemicalGroupBlockId = 7,
                            Name = "Nihonium",
                            OxidationStates = "+3, +1",
                            StandardState = "Solid",
                            Symbol = "Nh"
                        },
                        new
                        {
                            Id = 114,
                            AtomicMass = 290.19200000000001,
                            ChemicalGroupBlockId = 7,
                            Name = "Flerovium",
                            OxidationStates = "+6, +4, +2, +1, 0",
                            StandardState = "Solid",
                            Symbol = "Fl"
                        },
                        new
                        {
                            Id = 115,
                            AtomicMass = 290.19600000000003,
                            ChemicalGroupBlockId = 7,
                            Name = "Moscovium",
                            OxidationStates = "+3, +1",
                            StandardState = "Solid",
                            Symbol = "Mc"
                        },
                        new
                        {
                            Id = 116,
                            AtomicMass = 293.20499999999998,
                            ChemicalGroupBlockId = 7,
                            Name = "Livermorium",
                            OxidationStates = "+4, +2, -2",
                            StandardState = "Solid",
                            Symbol = "Lv"
                        },
                        new
                        {
                            Id = 117,
                            AtomicMass = 294.21100000000001,
                            ChemicalGroupBlockId = 9,
                            Name = "Tennessine",
                            OxidationStates = "+5, +3, +1, -1",
                            StandardState = "Solid",
                            Symbol = "Ts"
                        },
                        new
                        {
                            Id = 118,
                            AtomicMass = 295.21600000000001,
                            ChemicalGroupBlockId = 10,
                            Name = "Oganesson",
                            OxidationStates = "+6, +4, +2, +1, 0, -1",
                            StandardState = "Gas",
                            Symbol = "Og"
                        });
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id of the post.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of the user who wrote the post.");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Category ID of the post.");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Content of the post.");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Time when the post has been posted.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("To check if post is deleted.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Title of the post.");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasComment("A post that an user can submit to the forum.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = new Guid("2d42ee05-aabf-44fa-91c8-d4f7cd258e44"),
                            CategoryId = 1,
                            Content = "Can someone explain the concept of resonance in organic chemistry and provide examples to illustrate its significance in the stability of molecules?",
                            DateTime = new DateTime(2024, 1, 5, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Decoding Organic Resonance"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = new Guid("fdeb91a2-491f-40b6-83f6-b0ff231f9253"),
                            CategoryId = 2,
                            Content = "I'm struggling to grasp the concept of Gibbs free energy. How does it relate to spontaneity in chemical reactions, and what are the key factors that affect it?",
                            DateTime = new DateTime(2023, 3, 5, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Demystifying Gibbs Free Energy"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = new Guid("fdeb91a2-491f-40b6-83f6-b0ff231f9253"),
                            CategoryId = 3,
                            Content = "What are the main differences between coordination compounds and complex ions? How do ligands influence the properties of coordination compounds?",
                            DateTime = new DateTime(2024, 2, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Unraveling Coordination Compounds"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = new Guid("8a0f20bd-0612-4f85-98c1-45bac15088eb"),
                            CategoryId = 4,
                            Content = "I need help understanding the principles behind chromatography techniques. How does high-performance liquid chromatography (HPLC) differ from gas chromatography (GC), and in what situations would one be preferred over the other?",
                            DateTime = new DateTime(2023, 3, 5, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "HPLC vs. GC: Need Guidance"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = new Guid("8a0f20bd-0612-4f85-98c1-45bac15088eb"),
                            CategoryId = 5,
                            Content = "Could someone explain the role of enzymes in biochemical reactions? How do factors like pH and temperature affect enzyme activity, and are there any real-world applications of this knowledge?",
                            DateTime = new DateTime(2024, 1, 21, 18, 35, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Cracking the Enzyme Code"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = new Guid("8a0f20bd-0612-4f85-98c1-45bac15088eb"),
                            CategoryId = 6,
                            Content = "I recently came across the term 'nanotechnology' in the context of chemistry. Can someone shed light on how nanotechnology intersects with chemistry, and what are some notable applications or advancements in this interdisciplinary field?",
                            DateTime = new DateTime(2024, 1, 1, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Nanotechnology"
                        });
                });

            modelBuilder.Entity("ChemJourney.Data.Models.PostReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id of the post reply.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User Id of the person who gave the reply.");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Content of the reply.");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2")
                        .HasComment("Time when the reply is given.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("To check if reply is deleted.");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasComment("Post ID to which the reply is associated.");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("PostReplies");

                    b.HasComment("Replies that are given to a post.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = new Guid("8a0f20bd-0612-4f85-98c1-45bac15088eb"),
                            Content = "Resonance in organic chemistry refers to the delocalization of electrons within a molecule, often represented by multiple resonance structures. This phenomenon enhances the stability of molecules by distributing electron density. An example is the resonance in benzene, where electrons are shared across all carbon atoms, contributing to the overall stability of the aromatic ring. Resonance is crucial for understanding molecular stability and reactivity in various organic compounds.",
                            DateTime = new DateTime(2024, 1, 5, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PostId = 1
                        });
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id of the quiz.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Category ID of the quiz.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Quiz description.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Title of the quiz.");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Quizzes");

                    b.HasComment("Quiz that users can solve.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Covers fundamental methods for measuring, separating, and identifying substances.",
                            Title = "Analytical Chemistry Basics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Explores gas laws, thermodynamics, kinetics, and quantum mechanics basics.",
                            Title = "Physical Chemistry Fundamentals"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Introduces organic compound structure, reactions, and functional groups.",
                            Title = "Introduction to Organic Chemistry"
                        });
                });

            modelBuilder.Entity("ChemJourney.Data.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id of the question.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Correct answer to the question,");

                    b.Property<string>("OptionFour")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Fourth option for the quiz question.");

                    b.Property<string>("OptionOne")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("First option for the quiz question.");

                    b.Property<string>("OptionThree")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Third option for the quiz question.");

                    b.Property<string>("OptionTwo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Second option for the quiz question.");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("The question given.");

                    b.Property<int>("QuizId")
                        .HasColumnType("int")
                        .HasComment("Quiz ID to which the question is associated with.");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");

                    b.HasComment("Questions that a quiz will contain.");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.QuizScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id of the user scores");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime2")
                        .HasComment("Date when the quiz was taken.");

                    b.Property<int>("QuizId")
                        .HasColumnType("int")
                        .HasComment("ID of the quiz.");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasComment("Score received from the quiz.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID of the user who took the quiz.");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizScores");

                    b.HasComment("Information about who took which quiz.");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Element", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.ChemicalGroupBlock", "ChemicalGroupBlock")
                        .WithMany("Elements")
                        .HasForeignKey("ChemicalGroupBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChemicalGroupBlock");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Post", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemJourney.Data.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.PostReply", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemJourney.Data.Models.Post", "Post")
                        .WithMany("PostReplies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Quiz", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.Category", "Category")
                        .WithMany("Quizzes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.QuizQuestion", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.QuizScore", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ChemJourney.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Category", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.ChemicalGroupBlock", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Post", b =>
                {
                    b.Navigation("PostReplies");
                });

            modelBuilder.Entity("ChemJourney.Data.Models.Quiz", b =>
                {
                    b.Navigation("QuizQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
